# Name of the workflow
name: Basic-CI

# When someone will push or make PR to this repository, this workflow will start
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
        # We are using shivammathur/setup-php@v1 public GitHub actions for keeping things easier
        # b2 aldatuta
      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          # This job will be running on php7.4 version
          php-version: '7.4'

          # For PHPUnit code coverage, we need xdebug
          coverage: xdebug

          # If we want to enable any other PHP extension we can add here
          extensions: xdebug, intl, pdo_mysql, pdo
          
      - name: Install composer and dependencies
        uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        env:
          TEST_NAME: Tests
          XDEBUG_MODE: coverage
        with:
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml
          php_extensions: xdebug
          args: tests --coverage-clover ./coverage.xml
       
      # For code coverage report we are uploading our code coverage report to scrutinizer
      - name: Downloading scrutinizer ocular.phar
        run: wget https://scrutinizer-ci.com/ocular.phar
        
      #- name: Fix code coverage paths
      #  run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml
        
      # Uploading reports for analysis
      - name: Uploading code coverage to scrutinize
        # nik run: php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        run: php ocular.phar code-coverage:upload --format=php-clover ./coverage.xml
